# List of possible places honeyfused can deploy and mount decoy directories
# Possible options and their target directory are:
#       - kube      : ~/.kube/config (Kubernetes clusters)
#       - aws       : ~/.aws/{credentials,config} (AWS Keys and config)
#       - azure     : ~/.azure/credentials.json (Azure auth keys)
#       - gcloud    : ~/.gcloud/application_default_credentials.json (Google cloud)
#       - terraform : ~/.terraform.d/credentials.tfrc.json (Terraform credentials)
#       - docker    : ~/.docker/config.json (Docker with base64 tokens)
#       - bitcoin   : ~/.bitcoin/{wallet.dat, bitcoin.conf}

targets:
  - kube     
  - aws      
  - azure    
  - gcloud   
  # - terraform
  # - docker   
  # - bitcoin  

decoys: 2
